### Localhost

### Authors

### Get all authors
GET http://localhost:3000/authors HTTP/1.1

### Get a author by id
GET http://localhost:3000/authors/646ef8b86a3207236ad89cc7 HTTP/1.1

### Create a author
POST http://localhost:3000/authors HTTP/1.1
Content-Type: application/json

{
  "firstName": "Sam",
  "lastName": "Pletain",
  "email": "test@gmail.com",
  "joinedOn": "2023-05-28T00:05:12Z"
}

### Update a author
PUT http://localhost:3000/authors/64713d92236f799f60e5d802 HTTP/1.1
Content-Type: application/json

{
  "firstName": "Samuel",
  "lastName": "Pletain",
  "email": "samuel.pletain@gmail.com"
}

### Delete a author
DELETE http://localhost:3000/authors/64714c0d134f0c2847020acc HTTP/1.1

### Render

### Get all authors
GET https://cse341-app2.onrender.com/authors HTTP/1.1

### Get a author by id
GET https://cse341-app2.onrender.com/authors/6465a918462368509b563b24 HTTP/1.1

### Create a author
POST https://cse341-app2.onrender.com/authors HTTP/1.1
Content-Type: application/json

{
  "firstName": "Samuel",
  "lastName": "Pletain",
  "email": "samuel.pletain@gmail.com"
}